### ISSUE TITLE
Displaying wrong time zone

### ISSUE THREAD

**Issue by tedma4** [zMeadz/chronomouse#3]
```javascript
getLocalInfo('615',{zone_display: 'area'}).time.zone 
```
Is returning the wrong time zone
it returns *GMT-6*, should be *CST*

**Comment by zMeadz** [comment]
Hey Ted,

From the Read Me:

> zone_display - string. Sets object.zone_display. Can be 'name' OR 'offset'. Displays zone by zone name or GMT offset. Default 'offset'.
> 
> `console.log ( getLocalInfo('615',{zone_display: 'area'}).time.zone );`
>`// CST`
> 
> `console.log ( getLocalInfo('615',{zone_display: 'offset'}).time.zone );`
>` // GMT-5`

Does that answer your question?

**Comment by tedma4** [comment]
No, I'm using 2.4.0 and both are returning GMt-6

```javascript
console.log ( getLocalInfo('615',{zone_display: 'area'}).time.zone );
// GMT-6

console.log ( getLocalInfo('615',{zone_display: 'offset'}).time.zone );
// GMT-6
```

**Comment by tedma4** [comment]
I get it now. Was using *area* instead of *name*

```javascript
console.log ( getLocalInfo('615',{zone_display: 'name'}).time.zone );
// CST

```
